# This file was generated by GoReleaser. DO NOT EDIT.
cask "ai-spec" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/JailtonJunior94/orchestrator/releases/download/v#{version}/ai-spec_#{version}_darwin_amd64.tar.gz"
      sha256 "74da2233b861441db8959a84cc651dbb19fddc27e58edb1853cbec471dacc2ab"
    end
    on_arm do
      url "https://github.com/JailtonJunior94/orchestrator/releases/download/v#{version}/ai-spec_#{version}_darwin_arm64.tar.gz"
      sha256 "ac653bbb68054c1b6a795e8b0634e03c9538396c046b24d3804c4dfef8e1609e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/JailtonJunior94/orchestrator/releases/download/v#{version}/ai-spec_#{version}_linux_amd64.tar.gz"
      sha256 "0543746a7c917428de56f53bf484d540ac384f9c8a379da1d8ba3cddc39ff397"
    end
    on_arm do
      url "https://github.com/JailtonJunior94/orchestrator/releases/download/v#{version}/ai-spec_#{version}_linux_arm64.tar.gz"
      sha256 "d901c83f6205cc2fa1cad13c2b393ee75a8fab2c123ba547088498b42c571609"
    end
  end

  name "ai-spec"
  desc "CLI para governanca de IA em projetos de software"
  homepage "https://github.com/JailtonJunior94/orchestrator"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ai-spec"

  # No zap stanza required

end
