# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AiSpec < Formula
  desc "CLI para governanca de IA em projetos de software"
  homepage "https://github.com/JailtonJunior94/orchestrator"
  version "0.21.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JailtonJunior94/orchestrator/releases/download/v0.21.0/ai-spec_0.21.0_darwin_amd64.tar.gz"
      sha256 "53616a65f3c5d837360aeaaab5cb65202e12f0bd57396f7924483b9c94f829e2"

      define_method(:install) do
        bin.install "ai-spec"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JailtonJunior94/orchestrator/releases/download/v0.21.0/ai-spec_0.21.0_darwin_arm64.tar.gz"
      sha256 "8ed592c15092250d8894c57b6c36821f4228d6e97022d121b3b89afffa17473b"

      define_method(:install) do
        bin.install "ai-spec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/JailtonJunior94/orchestrator/releases/download/v0.21.0/ai-spec_0.21.0_linux_amd64.tar.gz"
      sha256 "be492b8325566cf338a3fc9503cfb7aa376da38dd2c25bafefff1d0c7042c103"
      define_method(:install) do
        bin.install "ai-spec"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JailtonJunior94/orchestrator/releases/download/v0.21.0/ai-spec_0.21.0_linux_arm64.tar.gz"
      sha256 "b31725eb4ac2e042727164ae3a8f0ef7d3db1ba2813f4bcd7acde86382d27b68"
      define_method(:install) do
        bin.install "ai-spec"
      end
    end
  end

  def post_install
    (bin/"ai-spec").chmod(0755)
    system "xattr", "-dr", "com.apple.quarantine", "#{bin}/ai-spec"
    (bin/"ai-spec").chmod(0555)
  end
end
