# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AiSpec < Formula
  desc "CLI para governanca de IA em projetos de software"
  homepage "https://github.com/JailtonJunior94/orchestrator"
  version "0.9.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JailtonJunior94/orchestrator/releases/download/v0.9.1/ai-spec_0.9.1_darwin_amd64.tar.gz"
      sha256 "be45d5bd04c597da985373eb045ec05f2a74ef297d816c8fb23e9f5cb8b31719"

      define_method(:install) do
        bin.install "ai-spec"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JailtonJunior94/orchestrator/releases/download/v0.9.1/ai-spec_0.9.1_darwin_arm64.tar.gz"
      sha256 "3d6cc3da8449718b81bb424f288a7a7dc21a542ee71a92d4e494335ad8656d84"

      define_method(:install) do
        bin.install "ai-spec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/JailtonJunior94/orchestrator/releases/download/v0.9.1/ai-spec_0.9.1_linux_amd64.tar.gz"
      sha256 "ecae9d8c1ff1c502f075511a2b8cd681df98b0870f97b263285420b84d272b8d"
      define_method(:install) do
        bin.install "ai-spec"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JailtonJunior94/orchestrator/releases/download/v0.9.1/ai-spec_0.9.1_linux_arm64.tar.gz"
      sha256 "0a2f45df0a2f0f750508e0aefdef1baae3f0553b5a5eff8ecec7279de8308878"
      define_method(:install) do
        bin.install "ai-spec"
      end
    end
  end
end
