# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AiSpec < Formula
  desc "CLI para governanca de IA em projetos de software"
  homepage "https://github.com/JailtonJunior94/orchestrator"
  version "0.26.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JailtonJunior94/orchestrator/releases/download/v0.26.0/ai-spec_0.26.0_darwin_amd64.tar.gz"
      sha256 "fca8370270a27c06473b0b5f820005622821e0d0ab2285ebac22530c6dfabf28"

      define_method(:install) do
        bin.install "ai-spec"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JailtonJunior94/orchestrator/releases/download/v0.26.0/ai-spec_0.26.0_darwin_arm64.tar.gz"
      sha256 "8fa6e581200c02852a1e63e587183f6e73ce7c7df12606916c1a7505e5736f46"

      define_method(:install) do
        bin.install "ai-spec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/JailtonJunior94/orchestrator/releases/download/v0.26.0/ai-spec_0.26.0_linux_amd64.tar.gz"
      sha256 "9d57c9c499393497ba07c43f4942e623a47ee784a493263dedfae374a700fb36"
      define_method(:install) do
        bin.install "ai-spec"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JailtonJunior94/orchestrator/releases/download/v0.26.0/ai-spec_0.26.0_linux_arm64.tar.gz"
      sha256 "ee808187efaf2cd72893f8873a31cdab60adfbad4374c7af9ad6584ebb233adc"
      define_method(:install) do
        bin.install "ai-spec"
      end
    end
  end

  def post_install
    (bin/"ai-spec").chmod(0755)
    system "xattr", "-dr", "com.apple.quarantine", "#{bin}/ai-spec"
    (bin/"ai-spec").chmod(0555)
  end
end
